library(tidyverse)

# importing the NIBRS data (downloaded from the FBI website)
NIBRS_ACTIVITY_TYPE <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_ACTIVITY_TYPE.csv",col_types = cols(ACTIVITY_TYPE_CODE = col_factor(levels = c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11"))))

NIBRS_AGE <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_AGE.csv")

NIBRS_ARREST_TYPE <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_ARREST_TYPE.csv")

NIBRS_ARRESTEE <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_ARRESTEE.csv", col_types = cols(MULTIPLE_INDICATOR = col_factor(levels = c("N", "C", "M")), SEX_CODE = col_factor(levels = c("M","F"))))

NIBRS_ARRESTEE_WEAPON <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_ARRESTEE_WEAPON.csv")

NIBRS_ASSIGNMENT_TYPE <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_ASSIGNMENT_TYPE.csv", col_types = cols(ASSIGNMENT_TYPE_CODE = col_factor(levels = c("F", "G", "H", "I", "J", "K", "L"))))

NIBRS_BIAS_LIST <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_BIAS_LIST.csv")

NIBRS_BIAS_MOTIVATION <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_BIAS_MOTIVATION.csv")

NIBRS_CIRCUMSTANCES <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_CIRCUMSTANCES.csv", col_types = cols(CIRCUMSTANCES_TYPE = col_factor(levels = c("A", "J", "N"))))

NIBRS_CLEARED_EXCEPT <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_CLEARED_EXCEPT.csv", col_types = cols(CLEARED_EXCEPT_CODE = col_factor(levels = c("A", "B", "C", "D", "E", "N"))))

NIBRS_CRIMINAL_ACT <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_CRIMINAL_ACT.csv")

NIBRS_CRIMINAL_ACT_TYPE <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_CRIMINAL_ACT_TYPE.csv", 
                                    col_types = cols(CRIMINAL_ACT_CODE = col_factor(levels = c("B","C", "D", "E", "O", "P", "T", "U","N", "G", "J", "A", "F", "I", "S"))))

NIBRS_DRUG_MEASURE_TYPE <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_DRUG_MEASURE_TYPE.csv",col_types = cols(DRUG_MEASURE_CODE = col_factor(levels = c("GM", "KG", "OZ", "LB", "ML", "LT", "FO", "GL", "DU", "NP", "XX"))))

NIBRS_ETHNICITY <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_ETHNICITY.csv", col_types = cols(ETHNICITY_CODE = col_factor(levels = c("M", "H", "N", "U"))))

NIBRS_INJURY <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_INJURY.csv", col_types = cols(INJURY_CODE = col_factor(levels = c("B", "I", "L", "M", "N", "O", "T", "U"))))

NIBRS_JUSTIFIABLE_FORCE <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_JUSTIFIABLE_FORCE.csv", col_types = cols(JUSTIFIABLE_FORCE_CODE = col_factor(levels = c("A", "B", "C", "D", "E", "F", "G", "U"))))

NIBRS_LOCATION_TYPE <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_LOCATION_TYPE.csv", col_types = cols(LOCATION_CODE = col_factor(levels = c("01", "02", "03", "04", "05", "06", "07", "08", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "37", "38", "39", "40", "41", "42", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "09", "58", "00"))))

NIBRS_OFFENDER <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_OFFENDER.csv", col_types = cols(SEX_CODE = col_factor(levels = c("M", "F", "U"))))

NIBRS_OFFENSE <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_OFFENSE.csv", col_types = cols(ATTEMPT_COMPLETE_FLAG = col_factor(levels = c("C", "A"))))

NIBRS_OFFENSE_TYPE <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_OFFENSE_TYPE.csv")

NIBRS_PROP_DESC_TYPE <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_PROP_DESC_TYPE.csv")

NIBRS_PROP_LOSS_TYPE <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_PROP_LOSS_TYPE.csv")

NIBRS_PROPERTY <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_PROPERTY.csv")

NIBRS_PROPERTY_DESC <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_PROPERTY_DESC.csv")

NIBRS_RELATIONSHIP <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_RELATIONSHIP.csv", col_types = cols(RELATIONSHIP_CODE = col_factor(levels = c("AQ","BE", "BG", "CF", "CH", "CS", "EE", "ER", "FR", "GC", "GP", "HR", "IL", "NE", "OF", "OK", "PA", "RU", "SB","SC","SE","SP","SS","ST","VO","XS","XR"))))

NIBRS_SUSPECT_USING <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_SUSPECT_USING.csv")

NIBRS_VICTIM <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_VICTIM.csv")

NIBRS_VICTIM_CIRCUMSTANCES <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_VICTIM_CIRCUMSTANCES.csv")

NIBRS_VICTIM_INJURY <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_VICTIM_INJURY.csv")

NIBRS_VICTIM_OFFENDER_REL <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_VICTIM_OFFENDER_REL.csv")

NIBRS_VICTIM_INJURY <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_VICTIM_INJURY.csv")

NIBRS_VICTIM_TYPE <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_VICTIM_TYPE.csv", col_types = cols(VICTIM_TYPE_CODE = col_factor(levels = c("B", "F", "G", "I", "L", "O", "R", "S", "U"))))

NIBRS_WEAPON <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/NIBRS_WEAPON.csv")

REF_RACE <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/REF_RACE.csv")

REF_STATE <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN_data/REF_STATE.csv")

#########
# data cleaning. Creating 2 datasets according to the main division in the dataset, that being between arrestees and offenders.

# arrestees

arrestees<-NIBRS_ARRESTEE %>% 
  select(ARRESTEE_ID, INCIDENT_ID, ARREST_TYPE_ID, OFFENSE_TYPE_ID, AGE_NUM, SEX_CODE, RACE_ID, ETHNICITY_ID)

arrestees<-full_join(arrestees,NIBRS_ARREST_TYPE,by="ARREST_TYPE_ID") %>%
  select(ARRESTEE_ID, INCIDENT_ID, ARREST_TYPE_NAME, OFFENSE_TYPE_ID, AGE_NUM, SEX_CODE, RACE_ID, ETHNICITY_ID)

# shorten name of arrestees dataset
arr<-arrestees

arr<-full_join(arr,NIBRS_OFFENSE_TYPE,by="OFFENSE_TYPE_ID") %>%
  select(ARRESTEE_ID, INCIDENT_ID, ARREST_TYPE_NAME, OFFENSE_NAME, CRIME_AGAINST, OFFENSE_CATEGORY_NAME, AGE_NUM, SEX_CODE, RACE_ID, ETHNICITY_ID)

arr<-full_join(arr,REF_RACE,by="RACE_ID") %>%
  select(ARRESTEE_ID, INCIDENT_ID, ARREST_TYPE_NAME, OFFENSE_NAME, CRIME_AGAINST, OFFENSE_CATEGORY_NAME, AGE_NUM, SEX_CODE, RACE_CODE, RACE_DESC, ETHNICITY_ID)

arr<-full_join(arr,NIBRS_ETHNICITY,by="ETHNICITY_ID") %>%
  select(ARRESTEE_ID, ARREST_TYPE_NAME, OFFENSE_NAME, CRIME_AGAINST, OFFENSE_CATEGORY_NAME, AGE_NUM, SEX_CODE, RACE_CODE, ETHNICITY_CODE, ETHNICITY_NAME)

############

# offenders

off<-NIBRS_OFFENDER %>%
  select(OFFENDER_ID, INCIDENT_ID, AGE_NUM, SEX_CODE, RACE_ID, ETHNICITY_ID)

off<-full_join(off,NIBRS_OFFENSE,by="INCIDENT_ID") %>%
  select(OFFENDER_ID, OFFENSE_ID, INCIDENT_ID, OFFENSE_TYPE_ID, LOCATION_ID, AGE_NUM, SEX_CODE, RACE_ID, ETHNICITY_ID)

bias<-full_join(NIBRS_BIAS_LIST,NIBRS_BIAS_MOTIVATION,by="BIAS_ID")

off<-full_join(off,bias,by="OFFENSE_ID") %>%
  select(OFFENDER_ID, OFFENSE_ID, INCIDENT_ID, OFFENSE_TYPE_ID, LOCATION_ID, AGE_NUM, SEX_CODE, RACE_ID, ETHNICITY_ID,BIAS_CATEGORY,BIAS_DESC)

off<-full_join(off,NIBRS_OFFENSE_TYPE,by="OFFENSE_TYPE_ID") %>%
  select(OFFENDER_ID, OFFENSE_ID, INCIDENT_ID, OFFENSE_NAME, CRIME_AGAINST, OFFENSE_CATEGORY_NAME, LOCATION_ID, AGE_NUM, SEX_CODE, RACE_ID, ETHNICITY_ID,BIAS_CATEGORY,BIAS_DESC)

off<-full_join(off,NIBRS_LOCATION_TYPE,by="LOCATION_ID") %>%
  select(OFFENDER_ID, OFFENSE_ID, INCIDENT_ID, OFFENSE_NAME, CRIME_AGAINST, OFFENSE_CATEGORY_NAME, LOCATION_NAME, AGE_NUM, SEX_CODE, RACE_ID, ETHNICITY_ID,BIAS_CATEGORY,BIAS_DESC)

off<-full_join(off,REF_RACE,by="RACE_ID") %>%
  select(OFFENDER_ID, OFFENSE_ID, INCIDENT_ID, OFFENSE_NAME, CRIME_AGAINST, OFFENSE_CATEGORY_NAME, LOCATION_NAME, AGE_NUM, SEX_CODE, RACE_CODE, RACE_DESC, ETHNICITY_ID,BIAS_CATEGORY,BIAS_DESC)

off<-full_join(off,NIBRS_ETHNICITY,by="ETHNICITY_ID") %>%
  select(OFFENDER_ID, OFFENSE_ID, INCIDENT_ID, OFFENSE_NAME, CRIME_AGAINST, OFFENSE_CATEGORY_NAME, LOCATION_NAME, AGE_NUM, SEX_CODE, RACE_CODE, RACE_DESC, ETHNICITY_CODE, ETHNICITY_NAME,BIAS_CATEGORY,BIAS_DESC)

off<-full_join(off,NIBRS_CRIMINAL_ACT,by="OFFENSE_ID") %>%
  select(OFFENDER_ID, OFFENSE_ID, INCIDENT_ID, OFFENSE_NAME, CRIME_AGAINST, OFFENSE_CATEGORY_NAME, CRIMINAL_ACT_ID, LOCATION_NAME, AGE_NUM, SEX_CODE, RACE_CODE, RACE_DESC, ETHNICITY_CODE, ETHNICITY_NAME,BIAS_CATEGORY,BIAS_DESC)

off<-full_join(off,NIBRS_CRIMINAL_ACT_TYPE,by="CRIMINAL_ACT_ID") %>%
  select(OFFENDER_ID, OFFENSE_ID, INCIDENT_ID, OFFENSE_NAME, CRIME_AGAINST, OFFENSE_CATEGORY_NAME, CRIMINAL_ACT_CODE, CRIMINAL_ACT_NAME, LOCATION_NAME, AGE_NUM, SEX_CODE, RACE_CODE, RACE_DESC, ETHNICITY_CODE, ETHNICITY_NAME,BIAS_CATEGORY,BIAS_DESC)

off<-full_join(off,NIBRS_PROPERTY,by="INCIDENT_ID") %>%
  select(OFFENDER_ID, OFFENSE_ID, INCIDENT_ID, OFFENSE_NAME, CRIME_AGAINST, OFFENSE_CATEGORY_NAME, CRIMINAL_ACT_CODE, CRIMINAL_ACT_NAME, LOCATION_NAME, AGE_NUM, SEX_CODE, RACE_CODE, RACE_DESC, ETHNICITY_CODE, ETHNICITY_NAME,BIAS_CATEGORY,BIAS_DESC, PROPERTY_ID, PROP_LOSS_ID, STOLEN_COUNT, RECOVERED_COUNT)

off<-full_join(off,NIBRS_PROP_LOSS_TYPE,by="PROP_LOSS_ID") %>%
  select(OFFENDER_ID, OFFENSE_ID, INCIDENT_ID, OFFENSE_NAME, CRIME_AGAINST, OFFENSE_CATEGORY_NAME, CRIMINAL_ACT_CODE, CRIMINAL_ACT_NAME, LOCATION_NAME, AGE_NUM, SEX_CODE, RACE_CODE, RACE_DESC, ETHNICITY_CODE, ETHNICITY_NAME,BIAS_CATEGORY,BIAS_DESC, PROPERTY_ID, PROP_LOSS_NAME, STOLEN_COUNT, RECOVERED_COUNT)

off<-full_join(off,NIBRS_PROPERTY_DESC, by="PROPERTY_ID") %>%
  select(OFFENDER_ID, OFFENSE_ID, INCIDENT_ID, OFFENSE_NAME, CRIME_AGAINST, OFFENSE_CATEGORY_NAME, CRIMINAL_ACT_CODE, CRIMINAL_ACT_NAME, LOCATION_NAME, AGE_NUM, SEX_CODE, RACE_CODE, RACE_DESC, ETHNICITY_CODE, ETHNICITY_NAME,BIAS_CATEGORY,BIAS_DESC, PROPERTY_ID, PROP_LOSS_NAME, STOLEN_COUNT, RECOVERED_COUNT, PROP_DESC_ID, PROPERTY_VALUE)

off<-full_join(off,NIBRS_PROP_DESC_TYPE,by="PROP_DESC_ID") %>%
  select(OFFENDER_ID, OFFENSE_ID, INCIDENT_ID, OFFENSE_NAME, CRIME_AGAINST, OFFENSE_CATEGORY_NAME, CRIMINAL_ACT_CODE, CRIMINAL_ACT_NAME, LOCATION_NAME, AGE_NUM, SEX_CODE, RACE_CODE, RACE_DESC, ETHNICITY_CODE, ETHNICITY_NAME,BIAS_CATEGORY,BIAS_DESC, PROPERTY_ID, PROP_LOSS_NAME, STOLEN_COUNT, RECOVERED_COUNT, PROP_DESC_NAME, PROPERTY_VALUE)

NIBRS_VICTIM<-NIBRS_VICTIM %>%
  rename(VIC_AGE_NUM=AGE_NUM, VIC_SEX_CODE=SEX_CODE, VIC_RACE_ID=RACE_ID, VIC_ETHNICITY_ID=ETHNICITY_ID)

off<-full_join(off,NIBRS_VICTIM,by="INCIDENT_ID") %>%
  select(OFFENDER_ID, OFFENSE_ID, INCIDENT_ID, OFFENSE_NAME, CRIME_AGAINST, OFFENSE_CATEGORY_NAME, CRIMINAL_ACT_CODE, CRIMINAL_ACT_NAME, LOCATION_NAME, AGE_NUM, SEX_CODE, RACE_CODE, RACE_DESC, ETHNICITY_CODE, ETHNICITY_NAME,BIAS_CATEGORY,BIAS_DESC, PROPERTY_ID, PROP_LOSS_NAME, STOLEN_COUNT, RECOVERED_COUNT, PROP_DESC_NAME, PROPERTY_VALUE, VICTIM_ID, VICTIM_TYPE_ID, ASSIGNMENT_TYPE_ID, ACTIVITY_TYPE_ID, VIC_AGE_NUM, VIC_SEX_CODE, VIC_RACE_ID, VIC_ETHNICITY_ID)

off<-full_join(off,NIBRS_ACTIVITY_TYPE,by="ACTIVITY_TYPE_ID") %>%
  select(OFFENDER_ID, OFFENSE_ID, INCIDENT_ID, OFFENSE_NAME, CRIME_AGAINST, OFFENSE_CATEGORY_NAME, CRIMINAL_ACT_CODE, CRIMINAL_ACT_NAME, LOCATION_NAME, AGE_NUM, SEX_CODE, RACE_CODE, RACE_DESC, ETHNICITY_CODE, ETHNICITY_NAME,BIAS_CATEGORY,BIAS_DESC, PROPERTY_ID, PROP_LOSS_NAME, STOLEN_COUNT, RECOVERED_COUNT, PROP_DESC_NAME, PROPERTY_VALUE, VICTIM_ID, VICTIM_TYPE_ID, ASSIGNMENT_TYPE_ID, ACTIVITY_TYPE_NAME, VIC_AGE_NUM, VIC_SEX_CODE, VIC_RACE_ID, VIC_ETHNICITY_ID)

off<-full_join(off,NIBRS_ASSIGNMENT_TYPE,by="ASSIGNMENT_TYPE_ID") %>%
  select(OFFENDER_ID, OFFENSE_ID, INCIDENT_ID, OFFENSE_NAME, CRIME_AGAINST, OFFENSE_CATEGORY_NAME, CRIMINAL_ACT_CODE, CRIMINAL_ACT_NAME, LOCATION_NAME, AGE_NUM, SEX_CODE, RACE_CODE, RACE_DESC, ETHNICITY_CODE, ETHNICITY_NAME,BIAS_CATEGORY,BIAS_DESC, PROPERTY_ID, PROP_LOSS_NAME, STOLEN_COUNT, RECOVERED_COUNT, PROP_DESC_NAME, PROPERTY_VALUE, VICTIM_ID, VICTIM_TYPE_ID, ASSIGNMENT_TYPE_NAME, VIC_AGE_NUM, VIC_SEX_CODE, VIC_RACE_ID, VIC_ETHNICITY_ID)

off<-full_join(off, NIBRS_VICTIM_CIRCUMSTANCES,by="VICTIM_ID") %>%
  select(OFFENDER_ID, OFFENSE_ID, INCIDENT_ID, OFFENSE_NAME, CRIME_AGAINST, OFFENSE_CATEGORY_NAME, CRIMINAL_ACT_CODE, CRIMINAL_ACT_NAME, LOCATION_NAME, AGE_NUM, SEX_CODE, RACE_CODE, RACE_DESC, ETHNICITY_CODE, ETHNICITY_NAME,BIAS_CATEGORY,BIAS_DESC, PROPERTY_ID, PROP_LOSS_NAME, STOLEN_COUNT, RECOVERED_COUNT, PROP_DESC_NAME, PROPERTY_VALUE, VICTIM_ID, VICTIM_TYPE_ID, CIRCUMSTANCES_ID, JUSTIFIABLE_FORCE_ID, ASSIGNMENT_TYPE_NAME, VIC_AGE_NUM, VIC_SEX_CODE, VIC_RACE_ID, VIC_ETHNICITY_ID)

off<-full_join(off,NIBRS_CIRCUMSTANCES,by="CIRCUMSTANCES_ID") %>%
  select(OFFENDER_ID, OFFENSE_ID, INCIDENT_ID, OFFENSE_NAME, CRIME_AGAINST, OFFENSE_CATEGORY_NAME, CRIMINAL_ACT_CODE, CRIMINAL_ACT_NAME, LOCATION_NAME, AGE_NUM, SEX_CODE, RACE_CODE, RACE_DESC, ETHNICITY_CODE, ETHNICITY_NAME,BIAS_CATEGORY,BIAS_DESC, PROPERTY_ID, PROP_LOSS_NAME, STOLEN_COUNT, RECOVERED_COUNT, PROP_DESC_NAME, PROPERTY_VALUE, VICTIM_ID, VICTIM_TYPE_ID, CIRCUMSTANCES_NAME, JUSTIFIABLE_FORCE_ID, ASSIGNMENT_TYPE_NAME, VIC_AGE_NUM, VIC_SEX_CODE, VIC_RACE_ID, VIC_ETHNICITY_ID)

off<-full_join(off, NIBRS_JUSTIFIABLE_FORCE,by= "JUSTIFIABLE_FORCE_ID") %>%
  select(OFFENDER_ID, OFFENSE_ID, INCIDENT_ID, OFFENSE_NAME, CRIME_AGAINST, OFFENSE_CATEGORY_NAME, CRIMINAL_ACT_CODE, CRIMINAL_ACT_NAME, LOCATION_NAME, AGE_NUM, SEX_CODE, RACE_CODE, RACE_DESC, ETHNICITY_CODE, ETHNICITY_NAME,BIAS_CATEGORY,BIAS_DESC, PROPERTY_ID, PROP_LOSS_NAME, STOLEN_COUNT, RECOVERED_COUNT, PROP_DESC_NAME, PROPERTY_VALUE, VICTIM_ID, VICTIM_TYPE_ID, CIRCUMSTANCES_NAME, JUSTIFIABLE_FORCE_CODE, JUSTIFIABLE_FORCE_NAME, ASSIGNMENT_TYPE_NAME, VIC_AGE_NUM, VIC_SEX_CODE, VIC_RACE_ID, VIC_ETHNICITY_ID)

off<-full_join(off,NIBRS_VICTIM_INJURY,by="VICTIM_ID") %>%
  select(OFFENDER_ID, OFFENSE_ID, INCIDENT_ID, OFFENSE_NAME, CRIME_AGAINST, OFFENSE_CATEGORY_NAME, CRIMINAL_ACT_CODE, CRIMINAL_ACT_NAME, LOCATION_NAME, AGE_NUM, SEX_CODE, RACE_CODE, RACE_DESC, ETHNICITY_CODE, ETHNICITY_NAME,BIAS_CATEGORY,BIAS_DESC, PROPERTY_ID, PROP_LOSS_NAME, STOLEN_COUNT, RECOVERED_COUNT, PROP_DESC_NAME, PROPERTY_VALUE, VICTIM_ID, VICTIM_TYPE_ID, CIRCUMSTANCES_NAME, INJURY_ID, JUSTIFIABLE_FORCE_CODE, JUSTIFIABLE_FORCE_NAME, ASSIGNMENT_TYPE_NAME, VIC_AGE_NUM, VIC_SEX_CODE, VIC_RACE_ID, VIC_ETHNICITY_ID)

off<-full_join(off,NIBRS_INJURY,by="INJURY_ID") %>%
  select(OFFENDER_ID, OFFENSE_ID, INCIDENT_ID, OFFENSE_NAME, CRIME_AGAINST, OFFENSE_CATEGORY_NAME, CRIMINAL_ACT_CODE, CRIMINAL_ACT_NAME, LOCATION_NAME, AGE_NUM, SEX_CODE, RACE_CODE, RACE_DESC, ETHNICITY_CODE, ETHNICITY_NAME,BIAS_CATEGORY,BIAS_DESC, PROPERTY_ID, PROP_LOSS_NAME, STOLEN_COUNT, RECOVERED_COUNT, PROP_DESC_NAME, PROPERTY_VALUE, VICTIM_ID, VICTIM_TYPE_ID, CIRCUMSTANCES_NAME, INJURY_NAME, JUSTIFIABLE_FORCE_CODE, JUSTIFIABLE_FORCE_NAME, ASSIGNMENT_TYPE_NAME, VIC_AGE_NUM, VIC_SEX_CODE, VIC_RACE_ID, VIC_ETHNICITY_ID)

off<-full_join(off,NIBRS_VICTIM_TYPE,by="VICTIM_TYPE_ID") %>%
  select(OFFENDER_ID, OFFENSE_ID, INCIDENT_ID, OFFENSE_NAME, CRIME_AGAINST, OFFENSE_CATEGORY_NAME, CRIMINAL_ACT_CODE, CRIMINAL_ACT_NAME, LOCATION_NAME, AGE_NUM, SEX_CODE, RACE_CODE, RACE_DESC, ETHNICITY_CODE, ETHNICITY_NAME,BIAS_CATEGORY,BIAS_DESC, PROPERTY_ID, PROP_LOSS_NAME, STOLEN_COUNT, RECOVERED_COUNT, PROP_DESC_NAME, PROPERTY_VALUE, VICTIM_ID, VICTIM_TYPE_NAME, CIRCUMSTANCES_NAME, INJURY_NAME, JUSTIFIABLE_FORCE_CODE, JUSTIFIABLE_FORCE_NAME, ASSIGNMENT_TYPE_NAME, VIC_AGE_NUM, VIC_SEX_CODE, VIC_RACE_ID, VIC_ETHNICITY_ID)

off<-full_join(off,NIBRS_VICTIM_OFFENDER_REL,by="VICTIM_ID") %>%
  select('OFFENDER_ID.x', OFFENSE_ID, INCIDENT_ID, OFFENSE_NAME, CRIME_AGAINST, OFFENSE_CATEGORY_NAME, CRIMINAL_ACT_CODE, CRIMINAL_ACT_NAME, LOCATION_NAME, AGE_NUM, SEX_CODE, RACE_CODE, RACE_DESC, ETHNICITY_CODE, ETHNICITY_NAME,BIAS_CATEGORY,BIAS_DESC, PROPERTY_ID, PROP_LOSS_NAME, STOLEN_COUNT, RECOVERED_COUNT, PROP_DESC_NAME, PROPERTY_VALUE, VICTIM_ID, VICTIM_TYPE_NAME, CIRCUMSTANCES_NAME, INJURY_NAME, JUSTIFIABLE_FORCE_CODE, JUSTIFIABLE_FORCE_NAME, ASSIGNMENT_TYPE_NAME, VIC_AGE_NUM, VIC_SEX_CODE, VIC_RACE_ID, VIC_ETHNICITY_ID, RELATIONSHIP_ID)

off<-rename(off,OFFENDER_ID=OFFENDER_ID.x)

off<-full_join(off,NIBRS_RELATIONSHIP,by="RELATIONSHIP_ID") %>%
  select(OFFENDER_ID, OFFENSE_ID, INCIDENT_ID, OFFENSE_NAME, CRIME_AGAINST, OFFENSE_CATEGORY_NAME, CRIMINAL_ACT_CODE, CRIMINAL_ACT_NAME, LOCATION_NAME, AGE_NUM, SEX_CODE, RACE_CODE, RACE_DESC, ETHNICITY_CODE, ETHNICITY_NAME,BIAS_CATEGORY,BIAS_DESC, PROPERTY_ID, PROP_LOSS_NAME, STOLEN_COUNT, RECOVERED_COUNT, PROP_DESC_NAME, PROPERTY_VALUE, VICTIM_ID, VICTIM_TYPE_NAME, CIRCUMSTANCES_NAME, INJURY_NAME, JUSTIFIABLE_FORCE_CODE, JUSTIFIABLE_FORCE_NAME, ASSIGNMENT_TYPE_NAME, VIC_AGE_NUM, VIC_SEX_CODE, VIC_RACE_ID, VIC_ETHNICITY_ID, RELATIONSHIP_CODE, RELATIONSHIP_NAME)

##########
# summary datasets

arr_sum <- arr %>%
  group_by(OFFENSE_CATEGORY_NAME) %>%
  summarise(n_arr=n())

off_sum <- off %>%
  group_by(OFFENSE_CATEGORY_NAME) %>%
  summarise(n_off=n())

arr_off_sum <- full_join(arr_sum,off_sum,by="OFFENSE_CATEGORY_NAME")

arr_off_sum <- arr_off_sum %>% 
  pivot_longer(c(`n_arr`, `n_off`), names_to = "Dataset", values_to = "n")

arr_race <- arr %>%
  group_by(RACE_CODE) %>%
  summarise(n_arr=n())

off_race <- off %>%
  group_by(RACE_CODE) %>%
  summarise(n_off=n())

arr_off_race <- full_join(arr_race,off_race,by="RACE_CODE")

arr_off_race <- arr_off_race %>% 
  pivot_longer(c(`n_arr`, `n_off`), names_to = "Dataset", values_to = "n")
