---
title: "Crime and policing in America"
author: "Samuel Carlen"
date: "6/23/2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,include=FALSE}
# importing the NIBRS data (downloaded from the FBI website)
NIBRS_ACTIVITY_TYPE <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN/NIBRS_ACTIVITY_TYPE.csv",col_types = cols(ACTIVITY_TYPE_CODE = col_factor(levels = c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11"))))

NIBRS_AGE <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN/NIBRS_AGE.csv")

NIBRS_ARREST_TYPE <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN/NIBRS_ARREST_TYPE.csv")

NIBRS_ARRESTEE <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN/NIBRS_ARRESTEE.csv", col_types = cols(MULTIPLE_INDICATOR = col_factor(levels = c("N", "C")), SEX_CODE = col_factor(levels = c("M","F"))))

NIBRS_ARRESTEE_WEAPON <- read_csv("//home/rstudio/courses/2019-20-semester2-mscs-264/Student A/carlen1/MSCS Final project/Crime_and_policing_in_America/MN/NIBRS_ARRESTEE_WEAPON.csv")
```

